/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aimee
 */
public class CalculadoradeGorjetas extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoradeGorjetas
     */
    public CalculadoradeGorjetas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        t_ValordaConta = new javax.swing.JLabel();
        t_ValordaGorjeta = new javax.swing.JLabel();
        btn_calcular = new javax.swing.JButton();
        t_ValorTotal = new javax.swing.JLabel();
        t_ResultadoValordaGorjeta = new javax.swing.JLabel();
        t_ResultadoValorTotal = new javax.swing.JLabel();
        btn_Limpar = new javax.swing.JButton();
        btn_Sair = new javax.swing.JButton();
        field_ValordaConta = new javax.swing.JTextField();
        field_PorcentagemGorjeta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        field_GorjetaDesejada = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calculadora de Gorjetas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        t_ValordaConta.setText("Valor da Conta:    R$");

        t_ValordaGorjeta.setText("Valor da gorjeta:");

        btn_calcular.setText("Calcular");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        t_ValorTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        t_ValorTotal.setText("VALOR TOTAL:");

        t_ResultadoValordaGorjeta.setText("-");

        t_ResultadoValorTotal.setText("-");

        btn_Limpar.setText("Limpar");
        btn_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimparActionPerformed(evt);
            }
        });

        btn_Sair.setText("Sair");
        btn_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SairActionPerformed(evt);
            }
        });

        field_PorcentagemGorjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_PorcentagemGorjetaActionPerformed(evt);
            }
        });

        jLabel7.setText("%");

        field_GorjetaDesejada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_GorjetaDesejadaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setText("Escreva a % ou o R$ desejado");

        jLabel2.setText("R$");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(t_ValordaConta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(field_ValordaConta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(t_ValorTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(t_ResultadoValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(field_PorcentagemGorjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(field_GorjetaDesejada, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 51, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btn_calcular))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(t_ValordaGorjeta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_ResultadoValordaGorjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btn_Limpar)
                        .addGap(64, 64, 64)
                        .addComponent(btn_Sair)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_ValordaConta)
                    .addComponent(field_ValordaConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_PorcentagemGorjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(field_GorjetaDesejada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(btn_calcular)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_ValordaGorjeta)
                    .addComponent(t_ResultadoValordaGorjeta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_ValorTotal)
                    .addComponent(t_ResultadoValorTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Limpar)
                    .addComponent(btn_Sair))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    double valorConta;
    double valorPorcentagem;
    
    
    
    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
  
        
        
        double valorDaConta;
        valorDaConta = Double.parseDouble(field_ValordaConta.getText());
        
        double valorDaPorcentagem; 
        
        double valorDaGorjeta;
        
        
        if (field_PorcentagemGorjeta.getText() != "") {
            valorDaPorcentagem = Double.parseDouble(field_PorcentagemGorjeta.getText());
            double valorTotal;
            valorTotal = valorDaConta + (valorDaConta*valorDaPorcentagem/100);
            t_ResultadoValorTotal.setText (String.valueOf(valorTotal));
            valorDaGorjeta = valorDaConta*valorDaPorcentagem/100;
            t_ResultadoValordaGorjeta.setText(String.valueOf(valorDaGorjeta));
        } 
        
        if (field_GorjetaDesejada.getText() != "") {
            valorDaGorjeta = Double.parseDouble(field_GorjetaDesejada.getText());
            double valorTotal;
            valorTotal = valorDaConta + valorDaGorjeta;
            t_ResultadoValorTotal.setText (String.valueOf(valorTotal));
            
        }
        
        
        
        
        
        /*
        double valorTotal1;
        valorTotal1 = valorDaConta + (valorDaConta*valorDaPorcentagem/100);
                
        double valorTotal2;
        valorTotal2 = valorDaConta + valorDaGorjeta;
        
        
        if (String.valueOf(valorTotal1) != "") {
            t_ResultadoValorTotal.setText (String.valueOf(valorTotal1));
        } else if (String.valueOf(valorTotal1) == "") {
            t_ResultadoValorTotal.setText (String.valueOf(valorTotal2));
        }
        
        /* double valorDaConta;
        valorDaConta = Double.parseDouble(field_ValordaConta.getText());
        
        double valorDaPorcentagem;
        valorDaPorcentagem = Double.parseDouble(field_PorcentagemGorjeta.getText());
        
        double valorDaGorjeta;
        valorDaGorjeta = Double.parseDouble(field_GorjetaDesejada.getText());
        
        if (String.valueOf(valorDaConta) != "" && String.valueOf(valorDaPorcentagem) != "") {
            double valorTotal1;
            valorTotal1 = valorDaConta + (valorDaConta*valorDaPorcentagem/100);
            t_ResultadoValorTotal.setText (String.valueOf(valorTotal1));
        } else if (String.valueOf(valorDaConta) != "" && String.valueOf(valorDaGorjeta) != ""){
            double valorTotal2;
            valorTotal2 = valorDaConta + valorDaGorjeta;
            t_ResultadoValorTotal.setText(String.valueOf(valorTotal2));
        }
        
     
        
        
        
      /*  double valorDaConta;
        valorDaConta = Double.parseDouble(field_ValordaConta.getText());
        
        double valorDaPorcentagem;
        valorDaPorcentagem = Double.parseDouble(field_PorcentagemGorjeta.getText());
        
        double valorDaGorjeta;
        valorDaGorjeta = Double.parseDouble(field_GorjetaDesejada.getText());
        
        double valorTotal1;
        valorTotal1 = valorDaConta + (valorDaConta*valorDaPorcentagem/100);
                
        double valorTotal2;
        valorTotal2 = valorDaConta + valorDaGorjeta;
        
        
        
        if (String.valueOf(valorTotal1) != "") {
            t_ResultadoValorTotal.setText (String.valueOf(valorTotal1));
        } else if (String.valueOf(valorTotal2) != "") {
            t_ResultadoValorTotal.setText(String.valueOf(valorTotal2));
        }
        
        
        */
        
        /* double valorTotal;
        double valorTotal2;
        
        if  (field_ValordaConta.getText()!= "" && field_GorjetaDesejada.getText()!= "") {
            double valorConta = Double.parseDouble(field_ValordaConta.getText());
            double valorGorjetaDesejada = Double.parseDouble(field_GorjetaDesejada.getText());
            valorTotal = valorConta + valorGorjetaDesejada;
            t_ResultadoValorTotal.setText(String.valueOf(valorTotal));
        } else if (field_ValordaConta.getText()!= "" && field_PorcentagemGorjeta.getText() != "") {
            double valorConta = Double.parseDouble(field_ValordaConta.getText());
            double valorPorcentagemGorjeta = Double.parseDouble(field_PorcentagemGorjeta.getText());
            valorTotal2 = valorConta + (valorConta*valorPorcentagemGorjeta/100);
            t_ResultadoValorTotal.setText(String.valueOf(valorTotal2));
        }
        /* double valorTotal;
        double valorTotal2;
        
        if (field_ValordaConta.getText()!= "" && field_GorjetaDesejada.getText()!= "") {
            double valorConta = Double.parseDouble(field_ValordaConta.getText());
            double valorGorjetaDesejada = Double.parseDouble(field_GorjetaDesejada.getText());
            valorTotal = valorConta + valorGorjetaDesejada;
            t_ResultadoValorTotal.setText(String.valueOf(valorTotal));
        } else if (field_ValordaConta.getText() != "" && field_PorcentagemGorjeta.getText() != "") {
            double valorConta = Double.parseDouble(field_ValordaConta.getText());
            double valorPorcentagemGorjeta = Double.parseDouble(field_PorcentagemGorjeta.getText());
            valorTotal2 = valorConta + (valorConta*valorPorcentagemGorjeta/100);
            t_ResultadoValorTotal.setText (String.valueOf(valorTotal2));
        }
        
        /*else if (field_ValordaConta.getText()!= "" && field_PorcentagemGorjeta.getText()!= ""); {
            double valorConta = Double.parseDouble(field_ValordaConta.getText());
            double valorPorcentagem = Double.parseDouble(field_PorcentagemGorjeta.getText());
            valorTotal = valorConta + (valorConta*valorPorcentagem/100);
            t_ResultadoValorTotal.setText(String.valueOf(valorTotal));
        }
        
        /*
        
        valorPorcentagem = Double.parseDouble(field_PorcentagemGorjeta.getText());
       
        //double valorGorjetaDesejada;
        
        System.out.println(valorConta);
        double valorDaGorjeta = (valorConta*valorPorcentagem/100);
        t_ResultadoValordaGorjeta.setText(String.valueOf(valorDaGorjeta));
        double valorTotal = valorConta+(valorConta*valorPorcentagem/100);
        t_ResultadoValorTotal.setText(String.valueOf(valorTotal));
        */
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void btn_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimparActionPerformed
        field_ValordaConta.setText("");
        field_PorcentagemGorjeta.setText("");
        field_GorjetaDesejada.setText("");
        t_ResultadoValordaGorjeta.setText ("");
        t_ResultadoValorTotal.setText ("");
        field_ValordaConta.requestFocus();
        
    }//GEN-LAST:event_btn_LimparActionPerformed

    private void btn_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_SairActionPerformed

    private void field_GorjetaDesejadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_GorjetaDesejadaActionPerformed
       valorConta = Double.parseDouble(field_ValordaConta.getText());
       double valorGorjetaDesejada;
       valorGorjetaDesejada = Double.parseDouble(field_GorjetaDesejada.getText());
       double valorConversao;
       valorConversao = (valorGorjetaDesejada/valorConta)*100;
       field_PorcentagemGorjeta.setText (String.valueOf(valorConversao));      
    }//GEN-LAST:event_field_GorjetaDesejadaActionPerformed

    private void field_PorcentagemGorjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_PorcentagemGorjetaActionPerformed
        valorConta = Double.parseDouble(field_ValordaConta.getText());
        valorPorcentagem = Double.parseDouble(field_PorcentagemGorjeta.getText());
        double valorDaGorjeta = valorConta*valorPorcentagem/100;
        field_GorjetaDesejada.setText (String.valueOf(valorDaGorjeta));
    }//GEN-LAST:event_field_PorcentagemGorjetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoradeGorjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoradeGorjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoradeGorjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoradeGorjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoradeGorjetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Limpar;
    private javax.swing.JButton btn_Sair;
    private javax.swing.JButton btn_calcular;
    private javax.swing.JTextField field_GorjetaDesejada;
    private javax.swing.JTextField field_PorcentagemGorjeta;
    private javax.swing.JTextField field_ValordaConta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel t_ResultadoValorTotal;
    private javax.swing.JLabel t_ResultadoValordaGorjeta;
    private javax.swing.JLabel t_ValorTotal;
    private javax.swing.JLabel t_ValordaConta;
    private javax.swing.JLabel t_ValordaGorjeta;
    // End of variables declaration//GEN-END:variables
}
